// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Zora = require("zora");

Zora.test("should run a test synchronously", (function (t) {
        t.equal(3.14, 3.14, "Should be a tasty dessert");
        
      }));

/*  Not a pure module */
