// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toString(prim) {
  return JSON.stringify(prim);
}

var J;

var B;

exports.J = J;
exports.B = B;
exports.toString = toString;
/* No side effect */
